name: ${name}
description: ${description}
author: ${author}
main: ${mainClass}
version: ${version}
url: ${url}
api-version: 1.18
commands:
  chi:
    description: "Removes your elemet and sets yours to chi."
    usage: /<command>
    permission: element.ChiCommand
