name: AutoElement
description: Automatically Selects Element When Player Logs In
author: TEXAPlayer
main: me.TEXAPlayer.AutoElement.Main
version: 1.0.0
url: https://github.com/xnusef/AutoElement
commands:
  example:
    aliases: ["ae"]
    description: "Auto Element."